=== muhammadfahad1817-cyber/DISM-WORK/XML/2/daraz.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="daraz">

    <xs:complexType>
        <xs:sequence>
            <xs:element name="products">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="product" maxOccurs="unbounded">
                        </xs:element>
                        <xs:element name="id">
                            <xs:simpleType>
                                <xs:restriction base="xs:int">
                                    <xs:minInclusive value="1"></xs:minInclusive>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="name" type="xs:string"></xs:element>
                        <xs:element name="description" type="xs:string"></xs:element>
                        <xs:element name="price">
                            <xs:simpleType>
                                <xs:restriction base="xs:int">
                                    <xs:minInclusive value="0"></xs:minInclusive>
                                    <xs:maxInclusive value="1000000"></xs:maxInclusive>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="customers">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="customer" maxOccurs="unbounded">
                             
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="id">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:int">
                                                <xs:minInclusive value="0"></xs:minInclusive>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                    <xs:element name="name" type="xs:string"></xs:element>
                                    <xs:element name="email" type="xs:string"></xs:element>
                                    <xs:element name="address" type="xs:string"></xs:element>
                                </xs:sequence>
                            </xs:complexType>
                       </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>


                      
       
           
        </xs:sequence>
    </xs:complexType>

 
    </xs:element>


</xs:schema>

=== muhammadfahad1817-cyber/DISM-WORK/XML/2/daraz.xml
<?xml version="1.0" encoding="UTF-8"?>

<daraz xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="daraz.xsd">

    <products>
        <product>1000</product>
        <id>1</id>
        <name>I phone</name>
        <description>Phone</description>
        <price>1000000</price>
    </products>


    <customers>
        <customer>
            <id>2</id>
            <name>Haris</name>
            <email>haris123@gmail.com</email>
            <address>House no 213</address>
        </customer>
        
    </customers>
</daraz>
