=== muhammadfahad1817-cyber/DISM-WORK/XML/1/students.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="students">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"></xs:element>
                            <xs:element name="age">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="1"></xs:minInclusive>
                                        <xs:maxInclusive value="100"></xs:maxInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="RollNumber" type="xs:int"></xs:element>
                            <xs:element name="marks">

                            <xs:simpleType>
                                <xs:restriction base="xs:int">
                                    <xs:minInclusive value="0"></xs:minInclusive>                       
                                    <xs:maxInclusive value="100"></xs:maxInclusive>
                                </xs:restriction>
                            </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== muhammadfahad1817-cyber/DISM-WORK/XML/1/students.xml
<?xml version="1.0" encoding="UTF-8"?>

<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="students.xsd">

    <student>
        <name>Ali</name>
        <age>100</age>
        <RollNumber>101</RollNumber>
        <marks>88</marks>
    </student>


       <student>
        <name>Sara</name>
        <age>45</age>
        <RollNumber>102</RollNumber>
        <marks>90</marks>
    </student>

</students>
